# -*- mode: ruby -*-
# vi: set ft=ruby  :

machines = {
  "master" => {"memory" => "1024", "cpu" => "1", "ip" => "200", "image" => "bento/ubuntu-24.04"},
  "node01" => {"memory" => "1024", "cpu" => "1", "ip" => "201", "image" => "bento/ubuntu-24.04"},
  "node02" => {"memory" => "1024", "cpu" => "1", "ip" => "202", "image" => "bento/ubuntu-24.04"}
}

Vagrant.configure("2") do |config|

  machines.each do |name, conf|
    config.vm.define "#{name}" do |machine|
      machine.vm.box = "#{conf["image"]}"
      machine.vm.hostname = "#{name}"
      machine.vm.network "public_network", ip: "192.168.1.#{conf["ip"]}"
      machine.vm.provider "virtualbox" do |vb|
        vb.name = "#{name}"
        vb.memory = conf["memory"]
        vb.cpus = conf["cpu"]
        
      end
      machine.vm.provision "shell", path: "ufw.sh"
      machine.vm.provision "shell", path: "docker.sh"
      machine.vm.provision "shell", path: "service.sh"
      
      config.vm.synced_folder "/var/lib/docker/volumes/myvolume/_data/", "/var/lib/docker/volumes/myvolume/_data/",
      type: "nfs",
      mount_options: ['actimeo=2']
      
      config.vm.synced_folder "/var/lib/docker/volumes/myvolume/_data/", "/var/lib/docker/volumes/myvolume/_data/",
      type: "nfs",
      linux__nfs_options: ['rw','subtree_check','sync']
      
      if "#{name}" == "master"
        
        machine.vm.provision "shell", path: "master.sh"
        machine.vm.provision "shell", path: "swarm.sh"
        
      else
        machine.vm.provision "shell", path: "worker.sh"
      end
      
      
      
    end
  end
end
